---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deploy
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: asp-testapp
        image: cuauhcodes/cuauh_codes_repo:5  # Replace with your Docker image
      imagePullSecrets:
      - name: dockauth
        ports:
        - containerPort: 80

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: testapp-svc
spec:
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer